[package]
name = "rust-shell"
version = "0.1.0"
authors = ["nickdutto <5254128+nickdutto@users.noreply.github.com>"]
edition = "2024"
rust-version = "1.95"

[dependencies]
comfy-table = "7.2.2"
# anyhow = "1.0.102"
# bytes = "1.11.1"
is_executable = "1.0.5"
jiff = "0.2.29"
nu-ansi-term = "0.50.3"
reedline = "0.48.0"
serde = "1.0.228"
thiserror = "2.0.18"
toml = "1.1.2"

[dev-dependencies]
rexpect = "0.7.1"
