[package]
name = "rust-shell"
version = "0.1.0"
authors = ["nickdutto <5254128+nickdutto@users.noreply.github.com>"]
edition = "2024"
rust-version = "1.95"

[profile.profiling]
inherits = "release"
debug = true
split-debuginfo = "off"
strip = "none"

[dependencies]
comfy-table = "7.2.2"
is_executable = "1.0.6"
jiff = "0.2.34"
miette = { version = "7.6.0", features = ["fancy"] }
nu-ansi-term = "0.50.3"
reedline = { version = "0.49.0", features = ["external_printer"] }
serde = "1.0.229"
thiserror = "2.0.19"
toml = "1.1.3"
unicode-segmentation = "1.13.3"
ureq = "3.3.0"
url = "2.5.8"

[dev-dependencies]
# rexpect = "0.7.1"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
if_not_else = "allow"
match_bool = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
single_match_else = "allow"
struct_excessive_bools = "allow"
struct_field_names = "allow"
too_many_arguments = "allow"
